{
 "title": "General Node Exporter",
 "description": "【English version】Update 2020.10.10, add the overall resource overview! Support Grafana6&7,Support Node Exporter v0.16 and above.Optimize the main metrics display. Includes: CPU, memory, disk IO, network, temperature and other monitoring metrics。https://github.com/starsliao/Prometheus",
 "tags": [
  "Prometheus",
  "node_exporter",
  "StarsL.cn"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({application=~\"$application\"},environment)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values({application=~\"$application\", environment=~\"$environment\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=~\"$job\",application=~\"$application\", environment=~\"$environment\"},instance)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "maxmount",
    "label": "maxmount",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$instance',node=~'$node',fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
    }
   },
   {
    "name": "total",
    "label": "total_servers",
    "query": {
     "query": "query_result(count(node_uname_info{instance=~\"$instance\"}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$instance\",job=~\"$job\",application=~\"$application\",environment=~\"$environment\"}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\",job=~\"$job\",application=~\"$application\",environment=~\"$environment\"}[$interval]))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=~\"$instance\",job=~\"$job\",application=~\"$application\",environment=~\"$environment\"}[$interval])) * 100"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=~\"$instance\",job=~\"$job\",application=~\"$application\",environment=~\"$environment\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\",job=~\"$job\",application=~\"$application\",environment=~\"$environment\"}) / node_memory_MemTotal_bytes{instance=~\"$instance\",job=~\"$job\",application=~\"$application\",environment=~\"$environment\"}) * 100"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min((node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\"$instance\",job=~\"$job\",application=~\"$application\",environment=~\"$environment\"} - node_filesystem_free_bytes{fstype=~\"xfs|ext4\",instance=~\"$instance\",job=~\"$job\",application=~\"$application\",environment=~\"$environment\"} )/ node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\"$instance\",job=~\"$job\",application=~\"$application\",environment=~\"$environment\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{job=~\"$job\",application=~\"$application\",instance=~\"$instance\",environment=~\"$environment\", mode='system'})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU iowait",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\",mode=\"iowait\"}[$interval])) * 100"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\",mode=\"idle\"}[$interval])) * 100)",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"} / (node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"})))* 100",
     "legendFormat": "Used RAM Memory"
    },
    {
     "expr": "(node_filesystem_size_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_avail_bytes {job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}+(node_filesystem_size_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}))",
     "legendFormat": "Used Max Mount($maxmount)"
    },
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"} + 1)/ (node_memory_SwapTotal_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"} + 1))) * 100",
     "legendFormat": "Used SWAP"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\".+\",job=~\"$job\",application=~\"$application\",environment=~\"$environment\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\",job=~\"$job\",application=~\"$application\",environment=~\"$environment\"}[$interval])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "FS Usage per Container",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{name=~\".+\",job=~\"$job\",application=~\"$application\",environment=~\"$environment\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "【$show_hostname】：Disk Space Used Basic(EXT?/XFS)",
   "type": "table-old",
   "description": "In this kanban: the total disk, usage, available, and usage rate are consistent with the values of the Size, Used, Avail, and Use% columns of the df command, and the value of Use% will be rounded to one decimal place, which will be more accurate .\n\nNote: The Use% algorithm in df is: (size-free) * 100 / (avail + (size-free)), the result is divisible by this value, non-divisible by this value is +1, and the unit of the result is %.\nRefer to the df command source code:",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "总量"
    },
    {
     "expr": "node_filesystem_avail_bytes {job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",node=~\"$node\",environment=~\"$environment\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",node=~\"$node\",environment=~\"$environment\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {job=~\"$job\",instance=~\"$instance\",application=~\"$application\",node=~\"$node\",environment=~\"$environment\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",node=~\"$node\",environment=~\"$environment\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",node=~\"$node\",environment=~\"$environment\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  {
   "title": "Internet traffic per hour",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 23 },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}[60m])",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}[60m])",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  { "title": "Resource Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Server Resource Overview【JOB：$job，Total：$total】",
   "type": "table-old",
   "description": "Partition utilization, disk read, disk write, download bandwidth, upload bandwidth, if there are multiple network cards or multiple partitions, it is the value of the network card or partition with the highest utilization rate collected.\n\nCurrEstab: The number of TCP connections whose current status is ESTABLISHED or CLOSE-WAIT.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"} - 0",
     "legendFormat": "主机名"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"})by(instance)",
     "legendFormat": "运行时间"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"} - 0",
     "legendFormat": "总内存"
    },
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\",job=~\"$job\",mode='system'}) by (instance)",
     "legendFormat": "总核数"
    },
    {
     "expr": "node_load5{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\",mode=\"idle\"}[$interval])) by (instance)) * 100",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"} / (node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "max((node_filesystem_size_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "分区使用率"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}[$interval])) by (instance)",
     "legendFormat": "最大读取"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}[$interval])) by (instance)",
     "legendFormat": "最大写入"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"} - 0",
     "legendFormat": "连接数"
    },
    {
     "expr": "node_sockstat_TCP_tw{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}[$interval])*8) by (instance)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}[$interval])*8) by (instance)",
     "legendFormat": "上传带宽"
    }
   ]
  },
  {
   "title": "$job：Overall total 5m load & average CPU used%",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\", mode='system'})",
     "legendFormat": "CPU Cores"
    },
    {
     "expr": "sum(node_load5{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"})",
     "legendFormat": "Total 5m load"
    },
    {
     "expr": "avg(1 - avg(rate(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\",mode=\"idle\"}[$interval])) by (instance)) * 100",
     "legendFormat": "Overall average used%"
    }
   ]
  },
  {
   "title": "$job：Overall total memory & average memory used%",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"} - node_memory_MemAvailable_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"})",
     "legendFormat": "Total Used"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"} - node_memory_MemAvailable_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}) / sum(node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}))*100",
     "legendFormat": "Overall Average Used%"
    }
   ]
  },
  {
   "title": "$job：Overall total disk & average disk used%",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(avg(node_filesystem_size_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "Total Used"
    }
   ]
  },
  { "title": "Resource Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "CPU% Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\",mode=\"system\",application=~\"$application\",environment=~\"$environment\"}[$interval])) by (instance) *100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$instance\",job=~\"$job\",mode=\"user\",application=~\"$application\",environment=~\"$environment\"}[$interval])) by (instance) *100",
     "legendFormat": "User"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$instance\",job=~\"$job\",application=~\"$application\",environment=~\"$environment\",mode=\"iowait\"}[$interval])) by (instance) *100",
     "legendFormat": "Iowait"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"$instance\",job=~\"$job\",application=~\"$application\",environment=~\"$environment\",mode=\"idle\"}[$interval])) by (instance))*100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"} - node_memory_MemAvailable_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}",
     "legendFormat": "Avaliable"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"} / (node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"})))* 100",
     "legendFormat": "Used%"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "node_load1{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "timeseries",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}[$interval])",
     "legendFormat": "{{device}}_Read bytes"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}[$interval])",
     "legendFormat": "{{device}}_Written bytes"
    }
   ]
  },
  {
   "title": "Network bandwidth usage per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}[$interval])*8",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}[$interval])*8",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "bargauge",
   "description": "Sockets_used - Sockets currently in use\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_alloc - Allocated sockets\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nRetransSegs - TCP retransmission packets\n\nOutSegs - Number of packets sent by TCP\n\nInSegs - Number of packets received by TCP",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}",
     "legendFormat": "Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "rate(node_netstat_Tcp_InSegs{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}[$interval])",
     "legendFormat": "Tcp_InSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_OutSegs{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}[$interval])",
     "legendFormat": "Tcp_OutSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}[$interval])",
     "legendFormat": "Tcp_RetransSegs"
    }
   ]
  },
  {
   "title": "Open  File Descriptor(left)/Context switches(right)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filefd_allocated{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}",
     "legendFormat": "used filefd"
    },
    {
     "expr": "rate(node_context_switches_total{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}[$interval])",
     "legendFormat": "switches"
    }
   ]
  },
  {
   "title": "Disk IOps Completed（IOPS）",
   "type": "timeseries",
   "description": "Read/write completions per second\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}[$interval])",
     "legendFormat": "{{device}}_Reads completed"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}[$interval])",
     "legendFormat": "{{device}}_Writes completed"
    },
    {
     "expr": "node_disk_io_now{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os",
   "type": "timeseries",
   "description": "The time spent on I/O in the natural time of each second.（wall-clock time）",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 86 },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}[$interval])",
     "legendFormat": "{{device}}_ IO time"
    }
   ]
  },
  {
   "title": "Disk R/W Time(Reference: less than 100ms)(beta)",
   "type": "timeseries",
   "description": "Time spent on each read/write operation",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 86 },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}[$interval]) / rate(node_disk_reads_completed_total{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",node=~\"$node\",environment=~\"$environment\"}[$interval])",
     "legendFormat": "{{device}}_Read time"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}[$interval]) / rate(node_disk_writes_completed_total{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}[$interval])",
     "legendFormat": "{{device}}_Write time"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}[$interval])",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total{job=~\"$job\",instance=~\"$instance\",application=~\"$application\",environment=~\"$environment\"}[$interval])",
     "legendFormat": "{{device}}_加权"
    }
   ]
  }
 ]
}