{
 "title": "Platform Monitoring",
 "description": "【English version】Update 2020.10.10, add the overall resource overview! Support Grafana6&7,Support Node Exporter v0.16 and above.Optimize the main metrics display. Includes: CPU, memory, disk IO, network, temperature and other monitoring metrics。https://github.com/starsliao/Prometheus",
 "tags": [
  "Prometheus",
  "node_exporter",
  "StarsL.cn"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({application=~\"$application\"},environment)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({application=~\"$application\", environment=~\"$environment\"},instance)"
    }
   },
   {
    "name": "device",
    "label": "NIC",
    "query": {
     "query": "label_values(node_network_info{device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "Server Resource Overview",
   "type": "table-old",
   "description": "Partition utilization, disk read, disk write, download bandwidth, upload bandwidth, if there are multiple network cards or multiple partitions, it is the value of the network card or partition with the highest utilization rate collected.\n\nCurrEstab: The number of TCP connections whose current status is ESTABLISHED or CLOSE-WAIT.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_uname_info{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"} - 0",
     "legendFormat": "主机名"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"})by(instance)",
     "legendFormat": "运行时间"
    },
    {
     "expr": "node_memory_MemTotal_bytes{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"} - 0",
     "legendFormat": "总内存"
    },
    {
     "expr": "count(node_cpu_seconds_total{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\",mode='system'}) by (instance)",
     "legendFormat": "总核数"
    },
    {
     "expr": "node_load5{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\",mode=\"idle\"}[$interval])) by (instance)) * 100",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\", application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"} / (node_memory_MemTotal_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\", application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "max((node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\", application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\", application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {origin_prometheus=~\"$origin_prometheus\",job=~\"$job\", application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\", application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\", application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "分区使用率"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\", application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "最大读取"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\", application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "最大写入"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\", application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"} - 0",
     "legendFormat": "连接数"
    },
    {
     "expr": "node_sockstat_TCP_tw{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\", application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\", application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"}[$interval])*8) by (instance)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\", application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"}[$interval])*8) by (instance)",
     "legendFormat": "上传带宽"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\", mode='system'})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic(EXT?/XFS)",
   "type": "table-old",
   "description": "In this kanban: the total disk, usage, available, and usage rate are consistent with the values of the Size, Used, Avail, and Use% columns of the df command, and the value of Use% will be rounded to one decimal place, which will be more accurate .\n\nNote: The Use% algorithm in df is: (size-free) * 100 / (avail + (size-free)), the result is divisible by this value, non-divisible by this value is +1, and the unit of the result is %.\nRefer to the df command source code:",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "总量"
    },
    {
     "expr": "node_filesystem_avail_bytes {application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(1 - avg(rate(node_cpu_seconds_total{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\",mode=\"idle\"}[$interval])) by (instance)) *100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU% Basic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 13 },
   "targets": [
    {
     "expr": "avg(1 - avg(rate(node_cpu_seconds_total{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\",mode=\"idle\"}[$interval])) by (instance)) *100",
     "legendFormat": "Sum of all instances"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_memory_MemTotal_bytes{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"} - node_memory_MemFree_bytes{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"} - (node_memory_Cached_bytes{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"} + node_memory_Buffers_bytes{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(node_memory_MemTotal_bytes{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"} - node_memory_MemFree_bytes{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"} - (node_memory_Cached_bytes{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"} + node_memory_Buffers_bytes{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_disk_written_bytes_total{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"}[$interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "timeseries",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(rate(node_disk_read_bytes_total{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"}[$interval]))",
     "legendFormat": "Read bytes"
    },
    {
     "expr": "avg(rate(node_disk_written_bytes_total{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"}[$interval]))",
     "legendFormat": "Written bytes"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os",
   "type": "stat",
   "description": "The time spent on I/O in the natural time of each second.（wall-clock time）",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_disk_io_time_seconds_total{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"}[$interval]))",
     "legendFormat": "IO time"
    }
   ]
  },
  {
   "title": "Disk IOps Completed（IOPS）",
   "type": "timeseries",
   "description": "Read/write completions per second\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "avg(rate(node_disk_reads_completed_total{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"}[$interval]))",
     "legendFormat": "Reads completed"
    },
    {
     "expr": "avg(rate(node_disk_writes_completed_total{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"}[$interval]))",
     "legendFormat": "Writes completed"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "avg(node_load1{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"})",
     "legendFormat": "1m"
    },
    {
     "expr": "avg(node_load5{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"})",
     "legendFormat": "5m"
    },
    {
     "expr": "avg(node_load15{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"})",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg(rate(node_network_receive_bytes_total{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\",device=~\"$device\"}[$interval])*8)",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "avg(rate(node_network_transmit_bytes_total{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\",device=~\"$device\"}[$interval])*8)",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "timeseries",
   "description": "Sockets_used - Sockets currently in use\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_alloc - Allocated sockets\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nRetransSegs - TCP retransmission packets\n\nOutSegs - Number of packets sent by TCP\n\nInSegs - Number of packets received by TCP",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(node_netstat_Tcp_CurrEstab{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"})",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "sum(node_sockstat_TCP_tw{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"})",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "sum(node_sockstat_sockets_used{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"})",
     "legendFormat": "Sockets_used"
    },
    {
     "expr": "sum(node_sockstat_UDP_inuse{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"})",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "sum(node_sockstat_TCP_alloc{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"})",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "sum(rate(node_netstat_Tcp_InSegs{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"}[$interval]))",
     "legendFormat": "Tcp_InSegs"
    },
    {
     "expr": "sum(rate(node_netstat_Tcp_OutSegs{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"}[$interval]))",
     "legendFormat": "Tcp_OutSegs"
    },
    {
     "expr": "sum(rate(node_netstat_Tcp_RetransSegs{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"}[$interval]))",
     "legendFormat": "Tcp_RetransSegs"
    }
   ]
  },
  {
   "title": "Open  File Descriptor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "avg(process_open_fds{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum(irate(nginx_http_requests_total[$interval]))",
     "legendFormat": "total qps"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nginx_connections_active{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Waiting Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nginx_connections_waiting{application=~\"$application\", environment=~\"$environment\", instance=~\"$instance\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 67 },
   "targets": [
    {
     "expr": "max(nginx_connections_active{instance=~\"$instance\"})",
     "legendFormat": "{{instance}} active"
    },
    {
     "expr": "max(nginx_connections_reading{instance=~\"$instance\"})",
     "legendFormat": "{{instance}} reading"
    },
    {
     "expr": "nginx_connections_waiting{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} waiting"
    },
    {
     "expr": "nginx_connections_writing{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} writing"
    }
   ]
  },
  {
   "title": "5XX",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_http_response_count_total{method=~\"POST\", status=\"500\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "GET: NON 200",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 74 },
   "targets": [
    {
     "expr": "nginx_http_response_count_total{method=~\"GET\", status=~\"^[0-1,3-9].*\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "200",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nginx_http_response_count_total{status=\"200\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "POST: NON 200",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 81 },
   "targets": [
    {
     "expr": "nginx_http_response_count_total{method=~\"POST\", status=~\"^[0-1,3-9].*\"}",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}