pipeline {
    agent any

    stages {
        stage("Test Application") {
            steps {
                script {
                    sh """
                    echo "Alhamdulillah"
                    """
                }
            }
        }
    }
}
