pipeline {
    agent any

    environment {
        jenkins_filepath="tf_runner/api-lookup"
        s3_bucket_name="spot-platform/redflag-api-lookup-prod"
    }

    stages {
        stage("Update AMI in config file") {
            steps {
                script {
                    sh """
                    cd "${env.jenkins_filepath}"
                    contents="\$(jq '.ami_id = "${params.ami_id}"' config.json)"
                    echo \$contents > config.json
                    """
                }
            }
        }

        stage("Pull TF state from S3") {
            steps {
                script {
                    sh """
                    cd "${env.jenkins_filepath}"
                    aws s3 cp "s3://${s3_bucket_name}/terraform.tfstate" ./tf_script --profile=spot-platform --region=us-east-1
                    """
                }
            }
        }

        stage("Terraform Init") {
            steps {
                script {
                    sh """
                    cd "${env.jenkins_filepath}/tf_script"
                    terraform init
                    """
                }
            }
        }

        stage("Terraform Validate") {
            steps {
                script {
                    sh """
                    cd "${env.jenkins_filepath}/tf_script"
                    terraform validate
                    """
                }
            }
        }

        stage("Terraform Apply") {
            steps {
                script {
                    sh """
                    cd "${env.jenkins_filepath}/tf_script"
                    export AWS_PROFILE=farhaan
                    terraform apply -auto-approve
                    """
                }
            }
        }

        stage("Push TF state to S3") {
            steps {
                script {
                    sh """
                    cd "${env.jenkins_filepath}"
                    aws s3 cp ./tf_script/terraform.tfstate "s3://${s3_bucket_name}/" --profile=spot-platform --region=us-east-1
                    """
                }
            }
        }
    }
}
