pipeline {
    agent any

    environment {
        jenkins_filepath="tf_runner/service-lookup"
    }

    stages {
        stage("Update AMI in config file") {
            steps {
                script {
                    sh """
                    cd "${env.jenkins_filepath}"
                    contents="\$(jq '.ami_id = "${params.ami_id}"' config.json)"
                    echo \$contents > config.json
                    """
                }
            }
        }

        stage("Pull TF state from S3") {
            steps {
                script {
                    sh """
                    echo "Executing AWS S3 cli command here"
                    """
                }
            }
        }

        stage("Terraform Init") {
            steps {
                script {
                    sh """
                    cd "${env.jenkins_filepath}/tf_script"
                    terraform init
                    """
                }
            }
        }

        stage("Terraform Validate") {
            steps {
                script {
                    sh """
                    cd "${env.jenkins_filepath}/tf_script"
                    terraform validate
                    """
                }
            }
        }

        stage("Teardown existing instances") {
            steps {
                script {
                    sh """
                    cd "${env.jenkins_filepath}"
                    contents="\$(jq '.spot_config.auto_scaling_group.desired_instances = 0' config.json)"
                    echo \$contents > config.json

                    export AWS_PROFILE=farhaan
                    cd "tf_script"
                    terraform apply -auto-approve
                    """
                }
            }
        }

        stage("Cool Down Period") {
            steps {
                script {
                    sh """
                    sleep 60
                    """
                }
            }
        }

        stage("Terraform Apply: Deploy new AMI") {
            steps {
                script {
                    sh """
                    cd "${env.jenkins_filepath}"
                    contents="\$(jq '.spot_config.auto_scaling_group.desired_instances = 3' config.json)"
                    echo \$contents > config.json

                    export AWS_PROFILE=farhaan
                    cd "tf_script"
                    terraform apply -auto-approve
                    """
                }
            }
        }

        stage("Warm Up Period") {
            steps {
                script {
                    sh """
                    sleep 60
                    """
                }
            }
        }

        stage("Push TF state to S3") {
            steps {
                script {
                    sh """
                    echo "Executing AWS S3 cli command here"
                    """
                }
            }
        }
    }
}
