pipeline {
    agent any

    environment {
        jenkins_filepath="tf_runner/redflag/dev/us-east-1/media-lookup"
    }

    stages {
        stage("Update AMI in config file") {
            steps {
                script {
                    sh """
                    cd "${env.jenkins_filepath}"
                    contents="\$(jq '.ami_id = "${params.ami_id}"' config.json)"
                    echo \$contents > config.json
                    """
                }
            }
        }

        stage("Pull TF state from S3") {
            steps {
                script {
                    sh """
                    echo "Executing AWS S3 cli command here"
                    """
                }
            }
        }

        stage("Terraform Init") {
            steps {
                script {
                    sh """
                    cd "${env.jenkins_filepath}/tf_script"
                    terraform init
                    """
                }
            }
        }

        stage("Terraform Validate") {
            steps {
                script {
                    sh """
                    cd "${env.jenkins_filepath}/tf_script"
                    terraform validate
                    """
                }
            }
        }

        stage("Terraform Apply: Teardown existing instances") {
            steps {
                script {
                    sh """
                    cd "${env.jenkins_filepath}/tf_script"
                    terraform apply -auto-approve
                    """
                }
            }
        }

        stage("Terraform Apply: Deploy new AMI") {
            steps {
                script {
                    sh """
                    cd "${env.jenkins_filepath}/tf_script"
                    terraform apply -auto-approve
                    """
                }
            }
        }

        stage("Push TF state to S3") {
            steps {
                script {
                    sh """
                    echo "Executing AWS S3 cli command here"
                    """
                }
            }
        }
    }
}
