pipeline {
    agent any

    environment {
        service="${params.SERVICE}"
        jenkins_filepath="scripts/load_testing/"
    }

    stages {
        stage("Creating virtual environment") {
            steps {
                script {
                    sh """
                    cd "${env.jenkins_filepath}/${service}"
                    virtualenv venv
                    """
                }
            }
        }

        stage("Installing requirements") {
            steps {
                script {
                    sh """
                    cd "${env.jenkins_filepath}/${service}"
                    . venv/bin/activate
                    pip3 install -r requirements.txt
                    """
                }
            }
        }

        stage("Running test cases") {
            steps {
                script {
                    sh """
                    cd "${env.jenkins_filepath}/${service}"
                    . venv/bin/activate
                    python3 main.py
                    """
                }
            }
        }

        stage("Test results") {
            steps {
                script {
                    sh """
                    cd "${env.jenkins_filepath}/${service}"
                    echo "Here are the test results"
                    """
                }
            }
        }

        stage("Cleanup") {
            steps {
                deleteDir()
            }
        }
    }
}
